.TH "testgeard" "1" "13 October 2014"

.SH "NAME"
testgeard \- The Test Gear server.

.SH "SYNOPSIS"
.PP
.B testgeard
[<options>]

.SH "DESCRIPTION"
.PP
.B testgeard
is the Test Gear server.

.SH "OPTIONS"

.TP
.B \-c, \--connection

Connection type (default: tcp).
.TP
.B \-p, \--tcp-port <port>

TCP listen port (default: 8000).
.TP
.B \-d, \--serial-device <device>

Serial device.
.TP
.B \-i, \--usb-id <vendor>:<product>

USB vendor and product ID.
.TP
.B \-D, \--daemon

Daemonize.
.TP
.B \-v, \--version

Display program version.
.TP
.B \-h, \--help

Display help.

.SH "AUTHOR"
.PP
Written by Martin Lund <martin.lund@keep-it-simple.com>.
